//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWOnlineCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int ID_ { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public string Title { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string Status { get; set; }
        public string Category { get; set; }
        public string Priority { get; set; }
        public Nullable<int> Customer { get; set; }
        public string ProblemDesc { get; set; }
        public Nullable<int> OpenedBy { get; set; }
    }
}
